openapi: 3.0.1
info:
  title: Prometheus exporter
  description: Export sFlow metrics in Prometheus format
  contact:
    name: sFlow-RT.com
    url: https://sflow-rt.com/
  version: 1.0.0
paths:
  /../../../prometheus/analyzer/txt:
    get:
      tags:
      - Analyzer
      summary: Get sFlow-RT performance metrics
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
              example: sflow_analyzer_agent_count 12
  /export.js/statistics/{group}/{agent}/{metric}/txt:
    get:
      tags:
      - Metrics
      summary: Get summary statistics
      parameters:
      - name: group
        in: path
        description: Label used group statistics
        required: true
        schema:
          type: string
        example: cluster 
      - name: agent
        in: path
        description: IP address(es) or ALL
        required: true
        style: simple
        explode: false
        schema:
          type: array
          items:
            type: string
        example:
        - ALL
      - name: metric
        description: Metric name(s)
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: array
          items:
            type: string
        example:
        - max:load_one
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
              example: sflow_max_load_one{group="cluster"} 11.2
  /../../../prometheus/statistics/{agent}/{metric}/txt:
    get:
      tags:
      - Metrics
      summary: Get metric values
      parameters:
      - name: agent
        in: path
        description: IP address(es) or ALL
        required: true
        style: simple
        explode: false
        schema:
          type: array
          items:
            type: string
        example:
        - ALL
      - name: metric
        description: Metric name(s) or ALL
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: array
          items:
            type: string
        example:
        - ALL
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
              example: sflow_ifinoctets{agent="192.168.0.11",datasource="15",ifname="swp10",host="leaf1"} 0
  /export.js/flows/{agent}/txt:
    get:
      tags:
        - Flows
      summary: Get flow values
      parameters:
      - name: agent
        in: path
        description: IP address(es) or ALL
        required: true
        style: simple
        explode: false
        schema:
          type: array
          items:
            type: string
        example:
        - ALL
      - name: metric
        in: query
        description: Metric name
        required: true
        schema:
          type: string
      - name: key
        in: query
        description: Flow key(s)
        required: true
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
        example:
        - ipsource
      - name: value
        in: query
        description: Flow value
        required: true
        schema:
          type: string
        example: bytes
      - name: filter
        in: query
        description: Filter flow attributes
        required: false
        schema:
          type: string
      - name: n
        in: query
        description: Number of largest flow entries to maintain
        required: false
        schema:
          type: integer
      - name: t
        in: query
        description: Smooting factor (in seconds)
        required: false
        schema:
          type: integer
      - name: label
        in: query
        description: Label flow key(s)
        required: false
        style: form
        explode: false
        schema:
          type: array
          items:
            type: string
      - name: aggMode
        in: query
        description: Method of aggregating duplicate flow records
        required: false
        schema:
          type: string
          enum: [sum,max]
      - name: maxFlows
        in: query
        description: Maximum number of flow records to return
        required: false
        schema:
          type: integer
      - name: minValue
        in: query
        description: Only report flows exceeding specified value
        required: false
        schema:
          type: float
      - name: scale
        in: query
        description: Scale values by specified amount
        required: false
        schema:
          type: float
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
              example: pair{src="10.0.0.1",dst="10.0.0.2"} 10.1
